# Resource section
resources:
- name: sources # Name of the resource
  type: git # Resource type
  source:
    uri: git@github.com:Hylke1982/DevOpsTraining.git
    private_key: ((private-repo-key))
    git_config:
    - name: core.sshCommand
      value: ssh -vvvv -o UserKnownHostsFile=/dev/null -o StrictHostKeyChecking=no

# Jobs section
jobs:
- name: build
  plan:
  - get: sources
    trigger: true
  - task: build software
    file: sources/CI/task-build.yml

- name: test # Name of the job
  plan:
  - get: sources # Download the sources
    trigger: true
    passed: [build] # Trigger after job build has passed
  - task: unit test
    file: sources/CI/task-unit-test.yml


- name: deploy # Name of the job
  plan:
  - get: sources # Download the sources
    trigger: true
    passed: [test] # Trigger after job test has passed
  - task: tag the version for release
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: openjdk, tag: 8-alpine}
      inputs:
        - name: sources
      run:
        path: ./gradlew
        args: ["tag", "-Prelease"]
        dir: sources/application
  - task: publish
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: openjdk, tag: 8-alpine}
      inputs:
        - name: sources
      run:
        path: ./gradlew
        args: ["uploadArchives"]
        dir: sources/application
  - task: update patch
    config:
      platform: linux
      image_resource:
        type: docker-image
        source: {repository: openjdk, tag: 8-alpine}
      inputs:
        - name: sources
      run:
        path: ./gradlew
        args: ["tag", "-PbumpComponent=patch"]
        dir: sources/application
  - put: sources # Push the tag
